esp_toml_version = 1.0

# Base URL of the file server where the images are available
firmware_images_url = "https://live-control-project.github.io/bin/"

supported_apps = ["OTDisplay"]

[OTDisplay]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "esp32s3_OTDisplay.bin"
ios_app_url = ""
android_app_url = ""
