esp_toml_version = 1.0

multipart = true
chip = "esp32-c6"
# Base URL of the file server where the images are available
firmware_images_url = "https://live-control-project.github.io/bin/"

supported_apps = ["ESP_matter_Controller"]

[ESP_matter_Controller]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "esp32h2_ot_rcp.bin"
ios_app_url = ""
android_app_url = ""
chipsets = ["ESP32-S3"]
image.esp32-s3 = "esp32s3_controller.bin"
ios_app_url = ""
android_app_url = ""
chipsets = ["ESP32-C6"]
image.esp32-c6 = "esp32c6_controller.bin"
ios_app_url = ""
android_app_url = ""
