esp_toml_version = 1.0

multipart = true
chip = "esp32-c6"
# Base URL of the file server where the images are available
firmware_images_url = "https://github.com/Live-Control-Project/ESP_MATTER_CONTROLLER/blob/main/bin/"

supported_apps = ["ESP32-H2", "ESP32-S3", "ESP32-C6"]

[ESP32-H2]
chipsets = ["ESP32-H2"]
image.esp32-h2 = "esp32h2_ot_rcp.bin"
ios_app_url = ""
android_app_url = ""

[ESP32-S3]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "esp32s3_controller.bin"
ios_app_url = ""
android_app_url = ""

[ESP32-C6]
chipsets = ["ESP32-C6"]
image.esp32-c6 = "esp32c6_controller.bin"
ios_app_url = ""
android_app_url = ""
